name: room_rental_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  lib: ^0.0.3
  validators: ^3.0.0
  crypto: ^3.0.6
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  firebase_app_check: ^0.4.1+2
  image_picker: ^1.2.0
  carousel_slider: ^5.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
